### PR TITLE
Some examples with covectors and some basic properties of next.

### PR DESCRIPTION
**Pull request by abizjak**
Working with covectors is quite difficult, but seems possible for the simple things I tried.

I proved some things about how later and Id type interact. In particular there is a proof that later Id implies Id of nexts. This only uses the (defined) induction principle for the Id type (the J rule).

For some of the properties it seems necessary to have the eta rule for next (the rule next [x <- t] x = t).
Not sure how important those properties are though.

### CODE REVIEW

**Comment by Saizan** [comment]
Ah, yes, without a system on next we should have eta rules for it, otherwise there's no other reasoning principle available.

I'll look into the escaped tag error, it's definitely a bug somewhere.

**Comment by Saizan** [comment]
Fixed!
By the way, are we happy that the following definition typechecks

```
idnext (A : U) (a b : |> A) (p : |> [x' <- a, y' <- b] (Id A x' y')) : Id (|> A) (next [x' <- a] x') (next [x' <- b] x')
   = <i> next [p' <- p] (p' @ i)
```

rather than needing to bind x' and y' in the local delayed substitution, like this?

```
   = <i> next [x' <- a, y' <- b, (p' : Id A x' y') <- p] (p' @ i)
```

The good thing is that they are definitionally equal.

**Comment by abizjak** [comment]
Thanks for fixing it.

I am not entirely happy that the definition 

```
idnext (A : U) (a b : |> A) (p : |> [x' <- a, y' <- b] (Id A x' y')) : Id (|> A) (next [x' <- a] x') (next [x' <- b] x')
    = <i> next [p' <- p] (p' @ i)
```

typechecks. At least I think with the rules we have in the paper (modulo a wishful extension with the cubical stuff) we would need to bind 

`= <i> next [x' <- a, y' <- b, (p' : Id A x' y') <- p] (p' @ i)`

as you say, because the term p' @ i is not typeable in the context without x' and y'. 

On the other hand I also don't see what could go wrong by allowing this, although it is not clear to me at the moment what the semantics of such a term without x' and y' would be.

**Comment by Saizan** [comment]
What's actually happening is that in both cases we get the following for `p'`
`p' : Id A x' y' (next x' = a, next y' = b)`
What's a bit sketchy is the way we justify the ability to form these thunks/delayed bindings `next x' = a`: we take care to only use them inside an outer `next` or `|>` by keeping track of the `Tag`s but that's only in the implementation.

Maybe we can just say that `[ a <- t ]` is elaborated to `xi[a <- t]` for  `t : |> xi A`, except the scope checker doesn't know about that.

**Comment by abizjak** [comment]
Unless we find something wrong I think your suggestion is a good one.

**Pull request merged**
